"""Fix relationship conflicts

Revision ID: 2737f4dd21ed
Revises: 3b0e0c232e72
Create Date: 2023-11-30 22:07:44.979174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2737f4dd21ed'
down_revision = '3b0e0c232e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_cuisines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_recipe_cuisines_cuisine_id_cuisines'), 'cuisines', ['cuisine_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_cuisines', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_recipe_cuisines_cuisine_id_cuisines'), type_='foreignkey')
        batch_op.drop_column('cuisine_id')

    # ### end Alembic commands ###
