"""debugging

Revision ID: 3b0e0c232e72
Revises: 5daa6f8182cf
Create Date: 2023-11-30 18:16:13.201023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0e0c232e72'
down_revision = '5daa6f8182cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('recipe_cuisines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipe_cuisines_cuisine_id_cuisines', type_='foreignkey')
        batch_op.drop_column('cuisine_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_cuisines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_recipe_cuisines_cuisine_id_cuisines', 'cuisines', ['cuisine_id'], ['id'])

    with op.batch_alter_table('chefs', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
