"""fix columns

Revision ID: 7a3a7cdc2f4f
Revises: 561aec49ca8c
Create Date: 2023-11-27 16:01:42.622731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a3a7cdc2f4f'
down_revision = '561aec49ca8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commendsadasts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commendsadasts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment_text', sa.VARCHAR(), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('chef_id', sa.INTEGER(), nullable=True),
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['chefs.id'], name='fk_commendsadasts_chef_id_chefs'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_commendsadasts_recipe_id_recipes'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
