"""debugging

Revision ID: 98456e5df599
Revises: a5e52e9abdb1
Create Date: 2023-11-30 11:48:27.316813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98456e5df599'
down_revision = 'a5e52e9abdb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###
