"""Fix relationship conflicts

Revision ID: 988487b6374e
Revises: 2737f4dd21ed
Create Date: 2023-11-30 23:11:16.301297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988487b6374e'
down_revision = '2737f4dd21ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('created_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
