"""3 Columns

Revision ID: a118e8add935
Revises: 55a0eceaaeb5
Create Date: 2023-11-28 09:35:30.087366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a118e8add935'
down_revision = '55a0eceaaeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cook_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instruction', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('instruction')
        batch_op.drop_column('cook_time')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
