"""add 3 columns

Revision ID: dd99d05b0233
Revises: b36675bb882e
Create Date: 2023-11-28 08:15:54.597700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd99d05b0233'
down_revision = 'b36675bb882e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cook_time', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('instruction', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('instruction')
        batch_op.drop_column('cook_time')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
